# Generated by Django 4.1.7 on 2023-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isClosed',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
