# Generated by Django 4.1.7 on 2023-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentHighestBid',
            field=models.FloatField(null=True),
        ),
    ]
