# Generated by Django 4.1.7 on 2023-02-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_currenthighestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
