# Generated by Django 4.1.7 on 2023-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='isHighest',
            field=models.BooleanField(auto_created=True, blank=True, null=True),
        ),
    ]
