# Generated by Django 4.1.7 on 2023-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_ishighest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='isHighest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
