# Generated by Django 4.1.7 on 2023-02-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_ishighest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='currentHighestBid',
            new_name='baseBid',
        ),
    ]
