# Generated by Django 4.1.7 on 2023-02-23 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_currenthighestbid_listing_basebid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('listingID', models.IntegerField(blank=True, null=True)),
                ('createdByUserID', models.IntegerField(blank=True, null=True)),
                ('isWatched', models.BooleanField(blank=True, null=True)),
                ('createdByUserKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listingKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
