# Generated by Django 4.1.7 on 2023-02-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='isWatched',
        ),
    ]
